#!/bin/bash
source $ROT/plugins/dstds-multi.conf
APP_ID=343050

function restart()
{
  for iCONF in $ROT/plugins/dstds-multi.*.conf; do
    source $iCONF
    send_cmd "c_shutdown()" $SESSION $WINDOW
    done

  for i in {1..10}; do
    BREAK=true
    sleep 10
    for iCONF in $ROT/plugins/dstds-multi.*.conf; do
      source $iCONF
      tail -n 1 $SERVER_LOG \
      | grep 'Shutting down' --silent \
      || BREAK=false
    done
    [ $BREAK = true ] && break
    [ $i = 10 ] && error '服务器未正常关闭'
  done

  for iCONF in $ROT/plugins/dstds-multi.*.conf; do
  source $iCONF
  send_cmd "$CMD" $SESSION $WINDOW
  done
}

function plugin_check()
{
  check "$INSTALL_DIR/version.txt"
  check "$SERVER_LOG"
  check "$START_SCRIPT"
}
